config/routes.rb
Rails.application.routes.draw do
  resources :before_followers
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'tops#index'
  
  # 静的ページ
  get 'static_pages/info'
  get 'static_pages/update'

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :followers do
    member do
      get 'update_followers_friends'
      get 'update_followers'
      get 'update_friends'
    end
    collection do
      get 'remove_index'
    end
  end

  resources :tops
  resources :user_options
  
  # その他のURLをエラーにする
  get '*anything' => 'errors#routing_error'
end

app/models/before_follower.rb
class BeforeFollower < ApplicationRecord
  belongs_to :user

  # フォロワーの状態チェック
  def check_status
    # 現在のフォロワー一覧に存在するか
    follower = Follower.find_by(user: self.user, uid: self.uid)
    self.remove_flg = true if follower.nil?
  end

  # 外れたフォロワーさん取得
  def self.remove_followers(user)
    BeforeFollower.where(user: user, remove_flg: true)
  end

end

app/controllers/before_followers_controller.rb
class BeforeFollowersController < InheritedResources::Base

  private

    def before_follower_params
      params.require(:before_follower).permit(:user_id, :uid, :name, :screen_name)
    end
end

app/views/before_followers/_form.html.slim
= simple_form_for(@before_follower) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user
    = f.input :uid
    = f.input :name
    = f.input :screen_name

  .form-actions
    = f.button :submit

app/views/before_followers/edit.html.slim
h1 Editing before_follower

== render 'form'

=> link_to 'Show', @before_follower
'|
=< link_to 'Back', before_followers_path

app/views/before_followers/index.html.slim
h1 Listing before_followers

table
  thead
    tr
      th User
      th Uid
      th Name
      th Screen name
      th
      th
      th

  tbody
    - @before_followers.each do |before_follower|
      tr
        td = before_follower.user
        td = before_follower.uid
        td = before_follower.name
        td = before_follower.screen_name
        td = link_to 'Show', before_follower
        td = link_to 'Edit', edit_before_follower_path(before_follower)
        td = link_to 'Destroy', before_follower, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Before follower', new_before_follower_path

app/views/before_followers/new.html.slim
h1 New before_follower

== render 'form'

= link_to 'Back', before_followers_path

app/views/before_followers/show.html.slim
p#notice = notice

p
  strong User:
  = @before_follower.user
p
  strong Uid:
  = @before_follower.uid
p
  strong Name:
  = @before_follower.name
p
  strong Screen name:
  = @before_follower.screen_name

=> link_to 'Edit', edit_before_follower_path(@before_follower)
'|
=< link_to 'Back', before_followers_path